### ISSUE TITLE
min and max values

### ISSUE THREAD

**Issue by tsov** [snapjay/angularjs-breakpoint#2]
Maybe we can introduce min and max values?

So imaging this

```
<body breakpoint="{'break1': [0, 480], 'break2': [481, 767], 'break3':[768, 979], 'break4':1200}">
```

So you can even specify ranges, like the `@media` tag in CSS3?

```
@media (min-width: 768px) and (max-width: 979px) { ... }
```

What do you think?

**Comment by snapjay** [comment]
I like idea of the mark up to mirror the @media tag representation;

If we do ranges then the script becomes susceptible to widths that don't have a defined class outside of the range. 

I think a responsive site by nature needs to consider all widths, the way it's setup up now may better encourages that behaviour

**Comment by tsov** [comment]
Thats fair enough, thought it might be a good option to give, since you could do it through CSS.
