### ISSUE TITLE
Broadcasting old value

### ISSUE THREAD

**Issue by apassant** [snapjay/angularjs-breakpoint#4]
```
            $rootScope.$broadcast('breakpointChange', scope.breakpoint);
```

Should be

```
            $rootScope.$broadcast('breakpointChange', scope.breakpoint, oldClass);
```

To broadcast the old value

**Comment by jasford** [comment]
I don't understand. It looks like the code was changed to match your suggestion a couple months before this issue was opened. Maybe this can simply be closed?

**Comment by apassant** [comment]
Indeed, that's weird. And that can be close, you're right
